	db	2, 0, "     BANK PANIC                         "
	db	6, 0, "     BOMB JACK                          "
	db	10, 0, "     BUCK ROGERS - PLANET OF ZOOM       "
	db	14, 0, "     CONGO BONGO                        "
	db	18, 0, "     CHAMPION BILLIARD                  "
	db	22, 0, "     CHAMPION BOXING                    "
	db	26, 0, "     CHAMPION ICE HOCKEY                "
	db	30, 0, "     CHAMPION PRO WRESTLING             "
	db	34, 0, "     CHAMPION SOCCER                    "
	db	36, 0, "     CHAMPIONSHIP KENDO                 "
	db	40, 0, "     DOKI DOKI PENGUIN LAND             "
	db	44, 0, "     FANTASY ZONE                       "
	db	60, 0, "     GP WORLD                           "
	db	64, 0, "     GULKAVE                            "
	db	68, 0, "     HANG-ON                            "
	db	72, 0, "     ORGUSS                             "
	db	76, 0, "     OUTRUN                             "
	db	108, 0, "     STAR TREK STRATEGIC OPERATIONS SIMU"
	db	112, 0, "     ZAXXON                             "
	db	116, 128, "     ZOOM 909                           "
	db	120, 255, "                                        " ; Do not modify this line
