	db	2, 0, "  ABU SIMBEL PROFANATION        "
	db	18, 0, "  ARMY MOVES                    "
	db	34, 0, "  ASPAR GP MASTER               "
	db	50, 0, "  ASTRO MARINE CORPS            "
	db	66, 0, "  BESTIAL WARRIOR               "
	db	82, 0, "  CAMELOT WARRIORS              "
	db	98, 0, "  COMANDO TRACER                "
	db	114, 0, "  FERNANDO MARTIN BASKET MASTER "
	db	122, 0, "  FREDDY HARDEST                "
	db	138, 0, "  GAME OVER II - PHANTIS        "
	db	154, 0, "  HUNDRA                        "
	db	170, 0, "  MICHEL FUTBOL MASTER          "
	db	186, 0, "  NAVY MOVES                    "
	db	202, 0, "  PHANTOMAS 2                   "
	db	218, 0, "  ROCKY                         "
	db	234, 128, "  TURBO GIRL                    "
	db	250, 255, "                                        " ; Do not modify this line
